// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "The Infinite Terrarium",
    defaultLocalization: "en",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Infinite Terrarium",
            targets: ["AppModule"],
            bundleIdentifier: "com.huangweijun.TheInfiniteTerrarium",
            teamIdentifier: "RD6P9386KT",
            displayVersion: "26.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .phone,
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeLeft,
                .landscapeRight
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(path: "Vendor/MarkdownPackages/swift-markdown-ui")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "MarkdownUI", package: "swift-markdown-ui")
            ],
            path: "Sources",
            resources: [
                .process("Assets.xcassets")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
